canonical/cluster-api-k8s

bootstrap/api/v1beta2/ck8sconfig_types.go, bootstrap/controllers/ck8sconfig_controller.go, controlplane/controllers/ck8scontrolplane_controller.go, controlplane/controllers/machine_controller.go, controlplane/controllers/remediation.go, controlplane/controllers/scale.go, controlplane/main.go, pkg/ck8s/api/cluster_node.go, pkg/ck8s/management_cluster.go, pkg/ck8s/workload_cluster.go, pkg/cloudinit/common.go, templates/docker/cluster-template.yaml
Remove nodes from microcluster and k8s when scaling down the cluster.
* Moved k8sd-proxy requests into generic separate function
* Added k8sd-proxy blacklist options to ensure the proxy is not targeting the machine that is removed
* Added `RemoveMachineFromCluster` method to workload cluster
Manual tests for now:
* Created 4 CP node cluster - removed 1 of them again
-> verified on remaining nodes that node is removed from microcluster and roles are updated
* Created 1 CP, 1 worker cluster - removed worker
-> verified that worker is removed from k8s
=> Cleanup microcluster/k8s when scaling down cluster nodes

bootstrap/controllers/ck8sconfig_controller.go
The microcluster port configuration was never propagated to the cloudinit configs. Previously the default port was set on the cloudinit level. This bug just surfaced because of moving the port config into `CK8sConfig` in #15
=> Fix microcluster port propagation

pkg/cloudinit/controlplane_init_test.go, pkg/cloudinit/controlplane_join_test.go, pkg/cloudinit/worker_join_test.go
Add unit tests for the `cloudinit` package.
These unit tests aim to validate the following aspects of cloudinit configurations:
- Expected commands within each config.
- Expected files within configs for:
- Initializing control planes
- Joining new control planes
- Joining new workers
=> Add unit tests for `cloudinit` generation

pkg/machinefilters/machine_filters.go, pkg/machinefilters/machine_filters_test.go
This has caused a broken cluster now for several times. Let's make sure we ignore the prefix in the comparison.
=> Ignore kubernetes version prefix for machine filter

templates/docker/Dockerfile, templates/docker/install-go.sh
Requires https://github.com/canonical/k8s-snap/pull/559
- Do not pull go1.21
- Automatically pick latest Go version from 1.22 track
=> Handle Go version used to build image

pkg/ck8s/api/annotations.go, pkg/ck8s/api/bootstrap_config.go, pkg/ck8s/config_init.go
This pull request addresses an issue where nodes are not properly drained in Cluster API before upgrades. The current CK8s remove hook removes the node from the Kubernetes cluster, which conflicts with the CAPI core controllers responsible for node removal within the CAPI context. As a result, when our controllers remove the node, the core controller loses track and only removes the resource reference in the management cluster.
This PR disables the Kubernetes node removal in the k8s-snap.
Requires https://github.com/canonical/k8s-snap/pull/577 to be merged. See there for more details.
=> disable k8s node cleanup and let CAPI handle it

pkg/ck8s/config_init.go
This caused a panic if the Annotations map was not set at all.
=> fix nil map assignment

templates/docker/cluster-template-dualstack.yaml
Adds a template to use for dualstack clusters.
The following steps where done to test with CAPD:
1. Create a dualstack network   
`sudo docker network create kind –ipv6 --driver=bridge -o com.docker.network.bridge.enable_ip_masquerade=true`  
(note that docker will ALWAYS use IPv4) \-\> `--ipv6` \== dualstack  
1. Generate cluster yaml from `templates/docker/cluster-template-dualstack.yaml`
```
KIND_IMAGE=k8s-snap:dev CONTROL_PLANE_MACHINE_COUNT=3 WORKER_MACHINE_COUNT=3 clusterctl generate cluster c1 --from ./templates/docker/cluster-template-dualstack.yaml  --kubernetes-version v1.30.3 > c1.yaml
```
1. Wait until all nodes/pods are up on workload cluster  
1. Deploy `nginx-dualstack.yaml` on the cluster  
`k8s kubectl apply -f https://raw.githubusercontent.com/canonical/k8s-snap/main/test …
=> Add dualstack template

templates/docker/Dockerfile, templates/docker/install-go.sh
old pattern could result in the following match which would cause a 404 during a docker build:
❯ curl -s https://go.dev/dl/ | grep -o "go1.22.*.linux-amd64.tar.gz"
go1.22.6.linux-amd64.tar.gz">go1.22.6.linux-amd64.tar.gz
=> use hardcoded Go version to get go from go.dev/dl in Dockerfile

pkg/ck8s/workload_cluster.go
This PR fixes the issue with CAPI rolling upgrades. The problem was that we were passing the wrong `node-name` to k8sd `remove-node` endpoint. 
CAPI rolling upgrades were failing, we narrowed down the problem, figured that the node removal process is not happening as expected (i.e. you can reproduce the problem by scaling down the control plane replicas of the workload cluster). Finally it was evident that the `/capi/remove-node` endpoint of k8sd was returning an error indicating that it can not find the node it was called to delete. That is because we were passing the `machine.Name` to k8sd `/capi/remove-node` endpoint, while as can be seen in the output of `kubectl get nodes` (of the workload cluster), we need to pass the node name.
=> Use Node name instead of Machine name on removal

bootstrap/controllers/ck8sconfig_controller.go, pkg/cloudinit/controlplane_join.go
This PR adds the token name to the extraSANs to make the microcluster token verification happy.
See https://github.com/canonical/k8s-snap/pull/629 for more context on why we need this.
Setup a test cluster with docker containers build from 
The cluster comes up and nodes are joining:
```
NAME                                                READY  SEVERITY  REASON  SINCE  MESSAGE
Cluster/c1                                          True                     20m
├─ClusterInfrastructure - DockerCluster/c1          True                     25m
├─ControlPlane - CK8sControlPlane/c1-control-plane  True                     20m
│ └─3 Machines...                                   True                     22m    See c1-control-plane-jrgpj, c1-control-plane-nl86p, ...
└─Workers …
```
=> Add join token to SANs

pkg/ck8s/config_init.go, pkg/ck8s/workload_cluster.go
We use `SkipCleanup` annotation to make sure k8sd does not remove the actual k8s node when calling `/x/capi/remove-node` endpoint so that CAPI core provider can take care of that. This PR makes sure the annotation is available in the cluster config everytime (currently we might end up not without the annotation).
Also there was a minor issue in the `doK8sdRequest` in which we tried to unmarshal metadata in a nil response.
=> Fix annotation, Skip nil response

bootstrap/config/rbac/role.yaml, bootstrap/controllers/upgrade_controller.go, hack/build-e2e-images.sh, templates/docker/Dockerfile, test/e2e/cluster_upgrade_test.go, test/e2e/common.go, test/e2e/config/ck8s-docker.yaml, test/e2e/helpers.go, test/e2e/in_place_upgrade_test.go
* Fixes missing rbac roles (Caused by a missing new line)
* Adds e2e tests for in-place upgrades on control-plane machines
* Adds e2e tests for in-place upgrades on worker machines
Note: The PR currently does not add the test to the github actions to run on PRs due to the cilium issue in `main` branch. As a workaround we could update `hack/build-e2e-images.sh` to point to the `autoupdate/moonray`.
=> Add in-place upgrade e2e tests

docs/proposals/000-template.md, docs/proposals/001-in-place-upgrades.md
=> Add in-place upgrade proposal

.github/workflows/e2e.yaml, hack/build-e2e-images.sh, test/e2e/helpers.go
Some e2e test improvements. See comments for each fix
=> Stabilize e2e tests

docs/proposals/002-cluster-controller.md
This PR adds the cluster-wide in-place upgrade proposal, a folllow-up on [the original in-place upgrade proposal](https://github.com/canonical/cluster-api-k8s/pull/30) and should be merged after that.
=> Add cluster-wide in-place upgrade proposal

go.mod, go.sum, pkg/ck8s/config_init.go, test/e2e/node_scale_test.go
This PR fixes a race condition that pops up if a workload cluster is scaled down. As part of the CK8s node removal, all services are stopped on the leaving node. This includes `kubelet` which causes the node to be reported as "not available" before the core CAPI controllers attempt to drain the node. 
By setting the annotation, we ensure that CAPI takes full control of the nodes removal process.
Note that we could also change the existing `skip-node-on-removal` annotation but there might be another use-case for just stopping services (+backward-compatibility).
Requires: 
https://github.com/canonical/k8s-snap/pull/682
https://github.com/canonical/k8s-snap-api/pull/8
=> Adapt scale test to not remove HA

controlplane/controllers/remediation.go
Fixes: `controlplane/controllers/remediation.go:377:6: function max has same name as predeclared identifier (predeclared)`
=> rename max to maxDuration to fix predeclared lint

bootstrap/controllers/ck8sconfig_controller.go, controlplane/controllers/ck8scontrolplane_controller.go, pkg/cloudinit/common.go, pkg/cloudinit/controlplane_init_test.go, pkg/cloudinit/controlplane_join_test.go, pkg/cloudinit/scripts/install.sh, pkg/cloudinit/worker_join_test.go
This PR adjusts the ck8s config reconciler to use the snap install option from an in-place upgrade release annotation if it exists. This can be utilized by adding the release annotation under the `CK8sControlPlane` or `MachineDeployment` specs, which will be propagated down to the machine.
For control-plane (CK8sControlPlane)
`.spec.machineTemplate.metadata.annotations => Machine.annotations`
Adopted something similar to [propagation logic from KCP](https://github.com/kubernetes-sigs/cluster-api/blob/377b79c272a660064b97745bad85a6f77bc7a2d2/controlplane/kubeadm/internal/controllers/controller.go#L644-L751)
For workers (MachineDeployment)
`.spec.template.metadata.annotations => MachineSet.spec.template.metadata.annotations  => Machine.annotations`
=> Use in-place upgrade release annotation if present

docs/002-refresh-certs.md, docs/proposals/003-refresh-certs.md
This proposal outlines a plan for refreshing certificates on cluster machines managed by Canonical Kubernetes CAPI providers.
=> Add Certs Refresh Proposal

docs/proposals/004-orchestration-refresh-certs.md
Add a proposal for implementing a cluster-wide certificates refresh in the Canonical Kubernetes providers
=> Add Cluster-wide Certificates Refresh

bootstrap/api/v1beta2/inplace_upgrade_consts.go, bootstrap/config/rbac/role.yaml, bootstrap/controllers/certificates_controller.go, bootstrap/controllers/machine_deployment_controller.go, bootstrap/controllers/upgrade_controller.go, bootstrap/main.go, pkg/trace/trace.go
This PR adds the `MachineDeploymentReconciler` according to the recent proposal. This controller is responsible for watching for `upgrade-to` annotation on `MachineDeployment` object and then handing down the annotation to its owned `Machine`s and wait for them to finish upgrading.
=> Add machine deployment reconciler

controlplane/api/v1beta2/ck8scontrolplane_types.go, controlplane/api/v1beta2/condition_consts.go, controlplane/controllers/ck8scontrolplane_controller.go, controlplane/controllers/machine_controller.go, controlplane/controllers/remediation.go, controlplane/controllers/scale.go, go.mod, pkg/ck8s/control_plane.go, pkg/ck8s/management_cluster.go, pkg/ck8s/workload_cluster.go, pkg/ck8s/workload_cluster_k8sd.go, pkg/locking/control_plane_init_mutex.go, pkg/proxy/dial.go, test/e2e/helpers.go
Removes unused etcd related commented out logic, conditions and variables
Updated errors to use `fmt.Errorf("foo: %w", err)`
Drop `github.com/pkg/errors` since standard library is enough for error wrapping currently
=> Remove unused code, comments and update errors to use fmt.Errorf

templates/aws/cluster-template.yaml
We now have a channel field we can use to specify the installation channel. This PR removes the install script overwrite and replaces it with the channel field.
=> Use new channel field instead of install script overwrite

go.mod, go.sum, pkg/ck8s/config_init.go
Update to use new location for annotations https://github.com/canonical/k8s-snap-api/pull/13
=> Use updated annotations from k8s api repo

test/e2e/helpers.go, test/e2e/machine_deployment_test.go
This PR adds the E2E tests for MachineDeployment Orchestrated In-Place Upgrades.
You can run this test specifically if you include a unique part of the description in `GINKGO_FOCUS`:
```bash
make GINKGO_FOCUS="\\[MD-InPlace\\]" test-e2e
```
=> Add E2E tests for MachineDeployment orchestrated in-place upgrades

.github/workflows/e2e.yaml, controlplane/config/rbac/role.yaml, controlplane/controllers/orchestrated_inplace_upgrade_controller.go, controlplane/main.go, pkg/upgrade/inplace/inplace.go, pkg/upgrade/inplace/interface.go, pkg/upgrade/inplace/lock.go, pkg/upgrade/inplace/mark.go, test/e2e/helpers.go, test/e2e/orchestrated_cp_in_place_upgrade_test.go
This PR adds the **orchestrated in-place upgrade controller** to the control plane provider.
After annotating the `CK8sControlPlane` object with `inplace-upgrade-to` annotation, this controller will make sure that each control plane machine is upgraded to the specified version.
By design, this controller does not allow parallel upgrades to ensure that the control plane stays responsive (prevent breaking HA, quorum, etc.)
- A lock (which is just a glorified configMap) prevents multiple control plane nodes getting upgraded
- Some of the common functionality is moved to `pkg/upgrade/inplace`. We should use these functionalities for the `MachineDeploymentReconciler` as well (instead of separately implementing them, which is what we're doing right now).
- Also the `MachineDeploymentReconciler` …
=> Add CP orchestrated in-place upgrade controller

.github/workflows/e2e.yaml
The `Build & Run E2E Images` job has to build various images and snaps for subsequent jobs, and thus, requires a quite a bit of storage. Some of the job failures occur simply because the set self-hosted runner runs out of space.
=> e2e: Increase runner size

pkg/ck8s/config_init.go
Fixes: https://github.com/canonical/cluster-api-k8s/issues/93
=> Add ck8scontrolplane extraSANs to the /capi/etc/config.yaml:extra-sans

bootstrap/config/manager/manager.yaml, bootstrap/config/rbac/auth_proxy_role_binding.yaml, bootstrap/config/rbac/kustomization.yaml, bootstrap/config/rbac/leader_election_role_binding.yaml, bootstrap/config/rbac/role_binding.yaml, bootstrap/config/rbac/service_account.yaml, controlplane/config/manager/manager.yaml, controlplane/config/rbac/auth_proxy_role_binding.yaml, controlplane/config/rbac/kustomization.yaml, controlplane/config/rbac/leader_election_role_binding.yaml, controlplane/config/rbac/role_binding.yaml, controlplane/config/rbac/service_account.yaml
The CIS 5.1.5 rule specifies: "Ensure that default service accounts are not actively used."
Currently, the default service account is being used. This adds the manager service account, resolving this issue.
Closes: https://github.com/canonical/cluster-api-k8s/issues/88
=> Adds non-default ServiceAccount

bootstrap/api/v1beta2/ck8sconfig_types.go, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_ck8sconfigs.yaml, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_ck8sconfigtemplates.yaml, bootstrap/controllers/ck8sconfig_controller.go, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_ck8scontrolplanes.yaml, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_ck8scontrolplanetemplates.yaml, pkg/ck8s/config_init.go, pkg/ck8s/config_join.go
The CAPI provider already allows passing extra kube-api args.
We'll do the same for the other k8s services (e.g. kubelet, kube-proxy, containerd, dqlite, etc), exposing the corresponding k8s-snap settings.
Fixes: https://github.com/canonical/cluster-api-k8s/issues/91
=> Allow passing extra service args

docs/release.md, metadata.yaml, test/e2e/config/ck8s-aws.yaml, test/e2e/config/ck8s-docker.yaml
Adds a brief tutorial on what to do for the CAPI provider release.
Does the actual updates for `0.3.0`
=> docs: Add pre-release steps and docs

test/e2e/intermediate_ca_test.go
The CAPI provider will either generate self-signed CA certificates or use the certificates specified through k8s secrets named {cluster-name}-{purpose}.
We'll add an e2e test that exercises this feature, passing intermediate CA certificates and ensuring that the cluster is properly bootstrapped.
Implements: KU-2512
=> Add intermediate CA e2e test

pkg/ck8s/workload_cluster.go
This PR suggests changes to remove the hard-coded URL path for K8sd RPC resources and replace them with the exposed variables from [K8s-snap-api](https://github.com/canonical/k8s-snap-api).
=> chore: Replace hard-coded URL paths with the ones from k8s-snap-api package

pkg/cloudinit/scripts/install.sh
The snap installation command for the local snap path is incorrect.
Closes: https://github.com/canonical/cluster-api-k8s/issues/105
=> Fixes local snap installation

.github/workflows/stale-cron.yaml
We're adding a nightly job that automatically closes PRs and issues that have been inactive for 6 months.
It applies an "inactive" label after 5 months and then proceeds to close them after another month.
=> CI: Automatically close inactive PRs and issues

.github/workflows/stale-cron.yaml
We're getting code scanning alerts as the stale job doesn't
contain explicit top-level permissions.
=> ci: add top level permissions to the stale job

.github/workflows/e2e.yaml, bootstrap/api/v1beta2/ck8sconfig_types.go, pkg/cloudinit/common.go
The following settings are enabled by default even if the network feature is disabled:
* EnableDefaultGateway
* EnableDefaultLoadBalancer
* EnableDefaultIngress
This causes bootstrap failures if the network feature is disabled.
To address this, we'll set these default values based on the network feature.
While at it, we'll fix the "BaseUserData" docstrings, clarifying the difference between the "BootstrapConfig" and "ConfigFileContents" fields.
Fixes: https://github.com/canonical/cluster-api-k8s/issues/106
=> bug: fix CK8sInitConfiguration defaults

bootstrap/api/v1beta2/ck8sconfig_types.go, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_ck8sconfigs.yaml, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_ck8sconfigtemplates.yaml, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_ck8scontrolplanes.yaml, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_ck8scontrolplanetemplates.yaml, pkg/cloudinit/scripts/install.sh
In airgapped environments, multiple snaps may be downloaded and then installed from local paths. The ``k8s`` snap depends on ``core20`` snap.
With this change, /capi/etc/snap-local-path may be a folder containing local snaps to install. This change preserved the old behaviour.
Fixes: https://github.com/canonical/cluster-api-k8s/issues/104
=> Allow multiple local path snaps to be installed

controlplane/controllers/remediation.go, controlplane/controllers/scale.go
If the microcluster request failed, we shouldn't proceed to remove the node's Machine, the node may still be registered as a node in the microcluster, leading it to becoming unhealthy and unstable.
=> Returns error when failing to remove machine from microcluster

test/e2e/node_scale_test.go, test/e2e/util.go
In the node scaling test, we are asserting the number of control plane nodes in the workload cluster after scaling the number. However, we do not check the k8sd cluster to see its view.
There have been cases in which the number of control plane nodes in the Kubernetes workload cluster does not match the number of nodes in the k8sd cluster. This will add some assertions, making sure those numbers match.
=> test: Assert the number of cluster members on node scaling test

pkg/cloudinit/scripts/configure-proxy.sh
The configure-proxy.sh script adds a superfluous "/tmp/" prefix to the proxy file paths:
```
HTTP_PROXY_FILE="/tmp/capi/etc/http-proxy"
HTTPS_PROXY_FILE="/tmp/capi/etc/https-proxy"
NO_PROXY_FILE="/tmp/capi/etc/no-proxy"
ENVIRONMENT_FILE="/tmp/etc/environment"
```
For this reason, the proxy settings are not applied correctly.
We'll fix the issue by simply removing the "/tmp/" prefix.
Fixes: https://github.com/canonical/cluster-api-k8s/issues/125
=> fix: use the correct proxy file locations

.github/workflows/cron-jobs.yaml, .github/workflows/lint_and_unit_tests.yaml
The unit test jobs are now failing, being unable to stop processes
as part of the test suite cleanup.
This was caused by recent changes in the `step-security/harden-runner@v2`
action.
To unblock the CI, we'll have to drop the `harden-runner` action.
Note that k8s-snap doesn't use it either.
While at it, we'll trigger the TICS cron job whenever the job
definition changes.
```
STEP: tearing down the test environment
Failure [0.001 seconds]
[AfterSuite] AfterSuite
/home/runner/work/cluster-api-k8s/cluster-api-k8s/bootstrap/controllers/suite_test.go:71
Unexpected error:
<errors.aggregate | len:2, cap:2>:
[unable to signal for process /home/runner/work/cluster-api-k8s/cluster-api-k8s/bin/k8s/1.32.0->      [
<*fmt.wrapError | 0xc00005ede0>{
msg: "unable to signal for process …
```
=> CI: fix unit test jobs

templates/docker/Dockerfile
When joining a Kubernetes cluster, k8sd tries to determine the Kubernetes version by checking the `bom.json` file included in the snap.
The docker template does not include that file, meaning that joining control plane nodes will fail to join because of this.
=> Adds bom.json file to the snap docker images

bootstrap/controllers/ck8sconfig_controller.go, controlplane/controllers/ck8scontrolplane_controller.go
In some cases, the resulting error is not handled / logged, and it should.
=> Fix error handling

pkg/ck8s/config_init.go
reverts the feature upgrade annotation that disabled the controller.
reverts #130 partially
=> fix: revert feature upgrade disable annotation

templates/aws/cluster-template.yaml, templates/aws/template-variables.rc, test/e2e/data/infrastructure-aws/cluster-template.yaml
This PR changes the LB type to `nlb` following the deprecation of the classic `elb`.
Upstream PRs:
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5338
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5345
This also updates the default root disk size in the AWS template to 40GB according to our [docs](https://documentation.ubuntu.com/canonical-kubernetes/latest/snap/tutorial/getting-started/). 
Fixes: https://github.com/canonical/cluster-api-k8s/issues/141
Fixes: https://github.com/canonical/cluster-api-k8s/issues/143
=> chore: (AWS) Change LB type to NLB following the deprecation of ELB

.github/workflows/tics.yaml
TIOBE recently changed the URL for the projects that use Golang. This pull request updates the URL and switches to a different workflow, as recommended by other projects.
=> fix: separate tics and use new action

templates/maas/cluster-template.yaml
This was needed for the demo to work.
=> fix(cluster-template/CK8sControlPlane): use spec.channel

templates/aws/cluster-template.yaml
Addresses https://github.com/canonical/cluster-api-k8s/issues/149
When no `channel` or revision is defined, the `classic/stable` [is set](https://github.com/canonical/cluster-api-k8s/blob/25065dd738b795bfe0addc83ea088988210c760c/pkg/cloudinit/common.go#L78-L84) as the default value.
=> chore: use the default classic/stable channel

.github/workflows/e2e.yaml, .github/workflows/lint_and_unit_tests.yaml, .github/workflows/sync-images.yaml, .golangci.yml, Makefile, bootstrap/controllers/certificates_controller.go, bootstrap/controllers/ck8sconfig_controller.go, bootstrap/controllers/upgrade_controller.go, controlplane/controllers/ck8scontrolplane_controller.go, controlplane/controllers/machine_controller.go, controlplane/controllers/remediation.go, controlplane/controllers/scale.go, go.mod, hack/tools/go.mod, pkg/ck8s/workload_cluster.go, templates/docker/Dockerfile
- Updates go version references in various different files to be derived from the `go.mod`
- Bumps go to 1.24
- Bumps golangci-lint to v2.3.0
- Fixes new static check errors detected after golangci-lint bump
=> chore: bump go to 1.24 and golanci-lint to v2.3.0

bootstrap/api/v1beta2/ck8sconfig_types.go, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_ck8sconfigs.yaml, bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_ck8sconfigtemplates.yaml, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_ck8scontrolplanes.yaml, controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_ck8scontrolplanetemplates.yaml, go.mod, go.sum, pkg/ck8s/config_init.go, templates/docker/Dockerfile
Should be rebased and merged after #171 and #172
=> feat: add managed etcd datastore option
